### ISSUE TITLE
Wrong number of response items

### ISSUE THREAD

**Issue by abulte** [lsbardel/python-stdnet#52]
I can not make this (nice looking!) library work, even with a very basic example:

``` python
from stdnet import odm

class Author(odm.StdModel):
    name = odm.SymbolField()

odm.register(Author, 'redis://localhost:6379?db=2')
a = Author(name='coucou')
a.save()
```

throws the exception:

```
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    a.save()
  File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/stdnet/odm/base.py", line 522, in save
    t.add(self)
  File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/stdnet/odm/session.py", line 384, in __exit__
    result = self.commit()
  File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/stdnet/odm/session.py", line 407, in commit
    return self.backend.execute_session(self.session, self.post_commit)
  File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/stdnet/backends/redisb.py", line 831, in execute_session
    command, result = redis_execution(pipe, session_result)
  File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/stdnet/backends/redisb.py", line 139, in redis_execution
    results = pipe.execute(load_script=True)
  File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/stdnet/lib/redis/client.py", line 1304, in execute
    return self.request(load_script).execute()
  File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/stdnet/lib/redis/connection.py", line 219, in execute
    return self.read_response()
  File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/stdnet/lib/redis/connection.py", line 237, in read_response
    response = self.parse(stream)
  File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/stdnet/lib/redis/connection.py", line 180, in parse
    return self.close()
  File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/stdnet/lib/redis/connection.py", line 158, in close
    response = self.client.parse_response(self)
  File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/stdnet/lib/redis/client.py", line 1278, in parse_response
    raise ResponseError("Wrong number of response items from "
NameError: global name 'ResponseError' is not defined
```

What am I doing wrong?

**Comment by lsbardel** [comment]
What version is it?

```
import stdnet
stdnet.__version__
```

**Comment by abulte** [comment]
```
>>> import stdnet
>>> stdnet.__version__
'0.7'
```

**Comment by lsbardel** [comment]
`ResponseError` is not defined and therefore that is a bug, not covered by the test suite.
But I don't understand why your script is hitting that part of the code. What OS are you using?

**Comment by abulte** [comment]
I'm using a Debian wheezy. 
Redis server version 2.2.12.
I can confirm my Redis install works fine because I use it successfully as a broker and result backend in a Celery task queue.

**Comment by lsbardel** [comment]
Ah!
your redis version is not supported by 0.7.
You need to upgrade to redis 2.6.x http://redis.io/download

http://lsbardel.github.com/python-stdnet/overview.html

**Comment by abulte** [comment]
And now it's a lot better ;-) Thanks very much for your help !
