### ISSUE TITLE
TypeError in  models.session().add( object ) ?

### ISSUE THREAD

**Issue by razaHamdani** [lsbardel/python-stdnet#79]
Hi guys,
           I am getting the following error when i try to add a model instance to the session.

Error:
TypeError: raise_first_error() takes exactly 3 arguments (2 given)

Raised when:
models = odm.Router('redis://localhost:6379?db=0')
models.session().add( my_object)  

Stdnet Version:
0.8.2

Python:
2.7

Redis:
2.9.0

Thanks

**Comment by autoscatto** [comment]
me too:

Stdnet Version:
0.8.2

Python:
2.7.6

Redis: 
2.8.7

TypeError: raise_first_error() takes exactly 3 arguments (2 given) in stdnet/backends/redisb/client.py:385

**Comment by surabujin** [comment]
Same issue here:

```
Traceback (most recent call last):
  File "/opt/pycharm-3.1.3/helpers/pydev/pydevd.py", line 1539, in <module>
    debugger.run(setup['file'], None, None)
  File "/opt/pycharm-3.1.3/helpers/pydev/pydevd.py", line 1150, in run
    pydev_imports.execfile(file, globals, locals) #execute the script
  File "/usr/share/devel/_dev_/stdnet-unique-check.py", line 30, in <module>
    sys.exit(main())
  File "/usr/share/devel/_dev_/stdnet-unique-check.py", line 26, in main
    make_chat('test')
  File "/usr/share/devel/_dev_/stdnet-unique-check.py", line 22, in make_chat
    models[Chat].new(**kwa)
  File "/usr/share/devel/_env_/local/lib/python2.7/site-packages/stdnet/odm/session.py", line 945, in new
    return self.session().add(self.model(*args, **kwargs))
  File "/usr/share/devel/_env_/local/lib/python2.7/site-packages/stdnet/odm/models.py", line 36, in __init__
    raise_kwargs(self, kwargs)
  File "/usr/share/devel/_env_/local/lib/python2.7/site-packages/stdnet/odm/base.py", line 540, in raise_kwargs
    raise ValueError("%s invalid keyword for %s." % (keys, model._meta))
ValueError: name is an invalid keyword for __main__.chat.
```
