### ISSUE TITLE
How to develop?

### ISSUE THREAD

**Issue by jbking** [lsbardel/python-stdnet#81]
With the master (d362bff9) branch seems passed at https://travis-ci.org/lsbardel/python-stdnet/jobs/16918109
But for now, testing with pulsar is failed even (0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.9.0) released and the rev (8e682b6d7)

This is with pulsar 0.9.0 released.

```
% python -m covrun
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/yusuke/src/python-stdnet/covrun.py", line 11, in <module>
    run()
  File "runtests.py", line 41, in run
    runtests(**params)
  File "runtests.py", line 56, in runtests
    suite.bind_event('tests', test.create_tests)
AttributeError: 'TestSuite' object has no attribute 'bind_event'
```

Which version of pulsar is usable? or needs something more for development?
I'm using Python 2.7.6 (homebrew) on Mac OSX Marvericks

**Comment by lsbardel** [comment]
Thanks for raising this issue.

Stdnet test-suite is built on top of [pulsar](https://github.com/quantmind/pulsar).
Pulsar has been developing fast over the last year, while `stdnet` has not.
The result is that the testing framework in `stdnet` needs upgrading to the new pulsar test API.
I'll try to have a look.
